// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID        string
	UserAID   string
	UserBID   string
	CreatedAt pgtype.Timestamptz
}

type Message struct {
	ID             string
	ConversationID string
	SenderID       string
	Ciphertext     string
	Nonce          string
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID        string
	Nickname  string
	PublicKey string
	Avatar    string
	CreatedAt pgtype.Timestamptz
}
