// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg *CreateMessageParams) (*Message, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	GetAllUsers(ctx context.Context, arg *GetAllUsersParams) ([]*User, error)
	GetConversationByID(ctx context.Context, id string) (*Conversation, error)
	GetConversationsByUserID(ctx context.Context, userAID string) ([]*Conversation, error)
	GetMessagesByConversationID(ctx context.Context, conversationID string) ([]*Message, error)
	GetOrCreateConversation(ctx context.Context, arg *GetOrCreateConversationParams) (*Conversation, error)
	GetPublicMessages(ctx context.Context, arg *GetPublicMessagesParams) ([]*GetPublicMessagesRow, error)
	GetUserByID(ctx context.Context, id string) (*User, error)
}

var _ Querier = (*Queries)(nil)
