// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, ciphertext, nonce)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_id, ciphertext, nonce, created_at
`

type CreateMessageParams struct {
	ConversationID string
	SenderID       string
	Ciphertext     string
	Nonce          string
}

func (q *Queries) CreateMessage(ctx context.Context, arg *CreateMessageParams) (*Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Ciphertext,
		arg.Nonce,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Ciphertext,
		&i.Nonce,
		&i.CreatedAt,
	)
	return &i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (nickname, public_key, avatar)
VALUES ($1, $2, $3)
RETURNING id, nickname, public_key, avatar, created_at
`

type CreateUserParams struct {
	Nickname  string
	PublicKey string
	Avatar    string
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Nickname, arg.PublicKey, arg.Avatar)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.PublicKey,
		&i.Avatar,
		&i.CreatedAt,
	)
	return &i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, nickname, public_key, avatar, created_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllUsers(ctx context.Context, arg *GetAllUsersParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, getAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.PublicKey,
			&i.Avatar,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, user_a_id, user_b_id, created_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id string) (*Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserAID,
		&i.UserBID,
		&i.CreatedAt,
	)
	return &i, err
}

const getConversationsByUserID = `-- name: GetConversationsByUserID :many
SELECT id, user_a_id, user_b_id, created_at
FROM conversations
WHERE user_a_id = $1 OR user_b_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetConversationsByUserID(ctx context.Context, userAID string) ([]*Conversation, error) {
	rows, err := q.db.Query(ctx, getConversationsByUserID, userAID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserAID,
			&i.UserBID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByConversationID = `-- name: GetMessagesByConversationID :many
SELECT id, conversation_id, sender_id, ciphertext, nonce, created_at
FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetMessagesByConversationID(ctx context.Context, conversationID string) ([]*Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByConversationID, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Ciphertext,
			&i.Nonce,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateConversation = `-- name: GetOrCreateConversation :one
INSERT INTO conversations (user_a_id, user_b_id)
VALUES ($1, $2)
ON CONFLICT (user_a_id, user_b_id) DO UPDATE SET user_a_id = EXCLUDED.user_a_id
RETURNING id, user_a_id, user_b_id, created_at
`

type GetOrCreateConversationParams struct {
	UserAID string
	UserBID string
}

func (q *Queries) GetOrCreateConversation(ctx context.Context, arg *GetOrCreateConversationParams) (*Conversation, error) {
	row := q.db.QueryRow(ctx, getOrCreateConversation, arg.UserAID, arg.UserBID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserAID,
		&i.UserBID,
		&i.CreatedAt,
	)
	return &i, err
}

const getPublicMessages = `-- name: GetPublicMessages :many
SELECT
    u_sender.nickname AS sender_nickname,
    u_recip.nickname  AS recipient_nickname,
    m.ciphertext,
    m.created_at
FROM messages m
JOIN conversations c ON m.conversation_id = c.id
JOIN users u_sender ON m.sender_id = u_sender.id
JOIN users u_recip ON (
    (c.user_a_id = m.sender_id AND u_recip.id = c.user_b_id) OR
    (c.user_b_id = m.sender_id AND u_recip.id = c.user_a_id)
)
WHERE ($1::timestamptz IS NULL OR m.created_at < $1)
ORDER BY m.created_at DESC
LIMIT $2
`

type GetPublicMessagesParams struct {
	Before pgtype.Timestamptz
	Limit  int32
}

type GetPublicMessagesRow struct {
	SenderNickname    string
	RecipientNickname string
	Ciphertext        string
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) GetPublicMessages(ctx context.Context, arg *GetPublicMessagesParams) ([]*GetPublicMessagesRow, error) {
	rows, err := q.db.Query(ctx, getPublicMessages, arg.Before, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetPublicMessagesRow
	for rows.Next() {
		var i GetPublicMessagesRow
		if err := rows.Scan(
			&i.SenderNickname,
			&i.RecipientNickname,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, nickname, public_key, avatar, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.PublicKey,
		&i.Avatar,
		&i.CreatedAt,
	)
	return &i, err
}
