// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i app/internal/repository.ConversationRepository -o conversation_repo_mock.go -n ConversationRepositoryMock -p mocks

import (
	"app/internal/models"
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ConversationRepositoryMock implements mm_repository.ConversationRepository
type ConversationRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetByID          func(ctx context.Context, id string) (cp1 *models.Conversation, err error)
	funcGetByIDOrigin    string
	inspectFuncGetByID   func(ctx context.Context, id string)
	afterGetByIDCounter  uint64
	beforeGetByIDCounter uint64
	GetByIDMock          mConversationRepositoryMockGetByID

	funcGetByUserID          func(ctx context.Context, userID string) (ca1 []models.Conversation, err error)
	funcGetByUserIDOrigin    string
	inspectFuncGetByUserID   func(ctx context.Context, userID string)
	afterGetByUserIDCounter  uint64
	beforeGetByUserIDCounter uint64
	GetByUserIDMock          mConversationRepositoryMockGetByUserID

	funcGetOrCreate          func(ctx context.Context, userAID string, userBID string) (cp1 *models.Conversation, err error)
	funcGetOrCreateOrigin    string
	inspectFuncGetOrCreate   func(ctx context.Context, userAID string, userBID string)
	afterGetOrCreateCounter  uint64
	beforeGetOrCreateCounter uint64
	GetOrCreateMock          mConversationRepositoryMockGetOrCreate
}

// NewConversationRepositoryMock returns a mock for mm_repository.ConversationRepository
func NewConversationRepositoryMock(t minimock.Tester) *ConversationRepositoryMock {
	m := &ConversationRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetByIDMock = mConversationRepositoryMockGetByID{mock: m}
	m.GetByIDMock.callArgs = []*ConversationRepositoryMockGetByIDParams{}

	m.GetByUserIDMock = mConversationRepositoryMockGetByUserID{mock: m}
	m.GetByUserIDMock.callArgs = []*ConversationRepositoryMockGetByUserIDParams{}

	m.GetOrCreateMock = mConversationRepositoryMockGetOrCreate{mock: m}
	m.GetOrCreateMock.callArgs = []*ConversationRepositoryMockGetOrCreateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mConversationRepositoryMockGetByID struct {
	optional           bool
	mock               *ConversationRepositoryMock
	defaultExpectation *ConversationRepositoryMockGetByIDExpectation
	expectations       []*ConversationRepositoryMockGetByIDExpectation

	callArgs []*ConversationRepositoryMockGetByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ConversationRepositoryMockGetByIDExpectation specifies expectation struct of the ConversationRepository.GetByID
type ConversationRepositoryMockGetByIDExpectation struct {
	mock               *ConversationRepositoryMock
	params             *ConversationRepositoryMockGetByIDParams
	paramPtrs          *ConversationRepositoryMockGetByIDParamPtrs
	expectationOrigins ConversationRepositoryMockGetByIDExpectationOrigins
	results            *ConversationRepositoryMockGetByIDResults
	returnOrigin       string
	Counter            uint64
}

// ConversationRepositoryMockGetByIDParams contains parameters of the ConversationRepository.GetByID
type ConversationRepositoryMockGetByIDParams struct {
	ctx context.Context
	id  string
}

// ConversationRepositoryMockGetByIDParamPtrs contains pointers to parameters of the ConversationRepository.GetByID
type ConversationRepositoryMockGetByIDParamPtrs struct {
	ctx *context.Context
	id  *string
}

// ConversationRepositoryMockGetByIDResults contains results of the ConversationRepository.GetByID
type ConversationRepositoryMockGetByIDResults struct {
	cp1 *models.Conversation
	err error
}

// ConversationRepositoryMockGetByIDOrigins contains origins of expectations of the ConversationRepository.GetByID
type ConversationRepositoryMockGetByIDExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByID *mConversationRepositoryMockGetByID) Optional() *mConversationRepositoryMockGetByID {
	mmGetByID.optional = true
	return mmGetByID
}

// Expect sets up expected params for ConversationRepository.GetByID
func (mmGetByID *mConversationRepositoryMockGetByID) Expect(ctx context.Context, id string) *mConversationRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("ConversationRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &ConversationRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.paramPtrs != nil {
		mmGetByID.mock.t.Fatalf("ConversationRepositoryMock.GetByID mock is already set by ExpectParams functions")
	}

	mmGetByID.defaultExpectation.params = &ConversationRepositoryMockGetByIDParams{ctx, id}
	mmGetByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByID.expectations {
		if minimock.Equal(e.params, mmGetByID.defaultExpectation.params) {
			mmGetByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByID.defaultExpectation.params)
		}
	}

	return mmGetByID
}

// ExpectCtxParam1 sets up expected param ctx for ConversationRepository.GetByID
func (mmGetByID *mConversationRepositoryMockGetByID) ExpectCtxParam1(ctx context.Context) *mConversationRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("ConversationRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &ConversationRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("ConversationRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &ConversationRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByID
}

// ExpectIdParam2 sets up expected param id for ConversationRepository.GetByID
func (mmGetByID *mConversationRepositoryMockGetByID) ExpectIdParam2(id string) *mConversationRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("ConversationRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &ConversationRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("ConversationRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &ConversationRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.id = &id
	mmGetByID.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetByID
}

// Inspect accepts an inspector function that has same arguments as the ConversationRepository.GetByID
func (mmGetByID *mConversationRepositoryMockGetByID) Inspect(f func(ctx context.Context, id string)) *mConversationRepositoryMockGetByID {
	if mmGetByID.mock.inspectFuncGetByID != nil {
		mmGetByID.mock.t.Fatalf("Inspect function is already set for ConversationRepositoryMock.GetByID")
	}

	mmGetByID.mock.inspectFuncGetByID = f

	return mmGetByID
}

// Return sets up results that will be returned by ConversationRepository.GetByID
func (mmGetByID *mConversationRepositoryMockGetByID) Return(cp1 *models.Conversation, err error) *ConversationRepositoryMock {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("ConversationRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &ConversationRepositoryMockGetByIDExpectation{mock: mmGetByID.mock}
	}
	mmGetByID.defaultExpectation.results = &ConversationRepositoryMockGetByIDResults{cp1, err}
	mmGetByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// Set uses given function f to mock the ConversationRepository.GetByID method
func (mmGetByID *mConversationRepositoryMockGetByID) Set(f func(ctx context.Context, id string) (cp1 *models.Conversation, err error)) *ConversationRepositoryMock {
	if mmGetByID.defaultExpectation != nil {
		mmGetByID.mock.t.Fatalf("Default expectation is already set for the ConversationRepository.GetByID method")
	}

	if len(mmGetByID.expectations) > 0 {
		mmGetByID.mock.t.Fatalf("Some expectations are already set for the ConversationRepository.GetByID method")
	}

	mmGetByID.mock.funcGetByID = f
	mmGetByID.mock.funcGetByIDOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// When sets expectation for the ConversationRepository.GetByID which will trigger the result defined by the following
// Then helper
func (mmGetByID *mConversationRepositoryMockGetByID) When(ctx context.Context, id string) *ConversationRepositoryMockGetByIDExpectation {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("ConversationRepositoryMock.GetByID mock is already set by Set")
	}

	expectation := &ConversationRepositoryMockGetByIDExpectation{
		mock:               mmGetByID.mock,
		params:             &ConversationRepositoryMockGetByIDParams{ctx, id},
		expectationOrigins: ConversationRepositoryMockGetByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByID.expectations = append(mmGetByID.expectations, expectation)
	return expectation
}

// Then sets up ConversationRepository.GetByID return parameters for the expectation previously defined by the When method
func (e *ConversationRepositoryMockGetByIDExpectation) Then(cp1 *models.Conversation, err error) *ConversationRepositoryMock {
	e.results = &ConversationRepositoryMockGetByIDResults{cp1, err}
	return e.mock
}

// Times sets number of times ConversationRepository.GetByID should be invoked
func (mmGetByID *mConversationRepositoryMockGetByID) Times(n uint64) *mConversationRepositoryMockGetByID {
	if n == 0 {
		mmGetByID.mock.t.Fatalf("Times of ConversationRepositoryMock.GetByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByID.expectedInvocations, n)
	mmGetByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByID
}

func (mmGetByID *mConversationRepositoryMockGetByID) invocationsDone() bool {
	if len(mmGetByID.expectations) == 0 && mmGetByID.defaultExpectation == nil && mmGetByID.mock.funcGetByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByID.mock.afterGetByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByID implements mm_repository.ConversationRepository
func (mmGetByID *ConversationRepositoryMock) GetByID(ctx context.Context, id string) (cp1 *models.Conversation, err error) {
	mm_atomic.AddUint64(&mmGetByID.beforeGetByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByID.afterGetByIDCounter, 1)

	mmGetByID.t.Helper()

	if mmGetByID.inspectFuncGetByID != nil {
		mmGetByID.inspectFuncGetByID(ctx, id)
	}

	mm_params := ConversationRepositoryMockGetByIDParams{ctx, id}

	// Record call args
	mmGetByID.GetByIDMock.mutex.Lock()
	mmGetByID.GetByIDMock.callArgs = append(mmGetByID.GetByIDMock.callArgs, &mm_params)
	mmGetByID.GetByIDMock.mutex.Unlock()

	for _, e := range mmGetByID.GetByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmGetByID.GetByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByID.GetByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByID.GetByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByID.GetByIDMock.defaultExpectation.paramPtrs

		mm_got := ConversationRepositoryMockGetByIDParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByID.t.Errorf("ConversationRepositoryMock.GetByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetByID.t.Errorf("ConversationRepositoryMock.GetByID got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByID.t.Errorf("ConversationRepositoryMock.GetByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByID.GetByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByID.t.Fatal("No results are set for the ConversationRepositoryMock.GetByID")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmGetByID.funcGetByID != nil {
		return mmGetByID.funcGetByID(ctx, id)
	}
	mmGetByID.t.Fatalf("Unexpected call to ConversationRepositoryMock.GetByID. %v %v", ctx, id)
	return
}

// GetByIDAfterCounter returns a count of finished ConversationRepositoryMock.GetByID invocations
func (mmGetByID *ConversationRepositoryMock) GetByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.afterGetByIDCounter)
}

// GetByIDBeforeCounter returns a count of ConversationRepositoryMock.GetByID invocations
func (mmGetByID *ConversationRepositoryMock) GetByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.beforeGetByIDCounter)
}

// Calls returns a list of arguments used in each call to ConversationRepositoryMock.GetByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByID *mConversationRepositoryMockGetByID) Calls() []*ConversationRepositoryMockGetByIDParams {
	mmGetByID.mutex.RLock()

	argCopy := make([]*ConversationRepositoryMockGetByIDParams, len(mmGetByID.callArgs))
	copy(argCopy, mmGetByID.callArgs)

	mmGetByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIDDone returns true if the count of the GetByID invocations corresponds
// the number of defined expectations
func (m *ConversationRepositoryMock) MinimockGetByIDDone() bool {
	if m.GetByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIDMock.invocationsDone()
}

// MinimockGetByIDInspect logs each unmet expectation
func (m *ConversationRepositoryMock) MinimockGetByIDInspect() {
	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ConversationRepositoryMock.GetByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIDCounter := mm_atomic.LoadUint64(&m.afterGetByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIDMock.defaultExpectation != nil && afterGetByIDCounter < 1 {
		if m.GetByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ConversationRepositoryMock.GetByID at\n%s", m.GetByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ConversationRepositoryMock.GetByID at\n%s with params: %#v", m.GetByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByID != nil && afterGetByIDCounter < 1 {
		m.t.Errorf("Expected call to ConversationRepositoryMock.GetByID at\n%s", m.funcGetByIDOrigin)
	}

	if !m.GetByIDMock.invocationsDone() && afterGetByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to ConversationRepositoryMock.GetByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIDMock.expectedInvocations), m.GetByIDMock.expectedInvocationsOrigin, afterGetByIDCounter)
	}
}

type mConversationRepositoryMockGetByUserID struct {
	optional           bool
	mock               *ConversationRepositoryMock
	defaultExpectation *ConversationRepositoryMockGetByUserIDExpectation
	expectations       []*ConversationRepositoryMockGetByUserIDExpectation

	callArgs []*ConversationRepositoryMockGetByUserIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ConversationRepositoryMockGetByUserIDExpectation specifies expectation struct of the ConversationRepository.GetByUserID
type ConversationRepositoryMockGetByUserIDExpectation struct {
	mock               *ConversationRepositoryMock
	params             *ConversationRepositoryMockGetByUserIDParams
	paramPtrs          *ConversationRepositoryMockGetByUserIDParamPtrs
	expectationOrigins ConversationRepositoryMockGetByUserIDExpectationOrigins
	results            *ConversationRepositoryMockGetByUserIDResults
	returnOrigin       string
	Counter            uint64
}

// ConversationRepositoryMockGetByUserIDParams contains parameters of the ConversationRepository.GetByUserID
type ConversationRepositoryMockGetByUserIDParams struct {
	ctx    context.Context
	userID string
}

// ConversationRepositoryMockGetByUserIDParamPtrs contains pointers to parameters of the ConversationRepository.GetByUserID
type ConversationRepositoryMockGetByUserIDParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// ConversationRepositoryMockGetByUserIDResults contains results of the ConversationRepository.GetByUserID
type ConversationRepositoryMockGetByUserIDResults struct {
	ca1 []models.Conversation
	err error
}

// ConversationRepositoryMockGetByUserIDOrigins contains origins of expectations of the ConversationRepository.GetByUserID
type ConversationRepositoryMockGetByUserIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByUserID *mConversationRepositoryMockGetByUserID) Optional() *mConversationRepositoryMockGetByUserID {
	mmGetByUserID.optional = true
	return mmGetByUserID
}

// Expect sets up expected params for ConversationRepository.GetByUserID
func (mmGetByUserID *mConversationRepositoryMockGetByUserID) Expect(ctx context.Context, userID string) *mConversationRepositoryMockGetByUserID {
	if mmGetByUserID.mock.funcGetByUserID != nil {
		mmGetByUserID.mock.t.Fatalf("ConversationRepositoryMock.GetByUserID mock is already set by Set")
	}

	if mmGetByUserID.defaultExpectation == nil {
		mmGetByUserID.defaultExpectation = &ConversationRepositoryMockGetByUserIDExpectation{}
	}

	if mmGetByUserID.defaultExpectation.paramPtrs != nil {
		mmGetByUserID.mock.t.Fatalf("ConversationRepositoryMock.GetByUserID mock is already set by ExpectParams functions")
	}

	mmGetByUserID.defaultExpectation.params = &ConversationRepositoryMockGetByUserIDParams{ctx, userID}
	mmGetByUserID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByUserID.expectations {
		if minimock.Equal(e.params, mmGetByUserID.defaultExpectation.params) {
			mmGetByUserID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByUserID.defaultExpectation.params)
		}
	}

	return mmGetByUserID
}

// ExpectCtxParam1 sets up expected param ctx for ConversationRepository.GetByUserID
func (mmGetByUserID *mConversationRepositoryMockGetByUserID) ExpectCtxParam1(ctx context.Context) *mConversationRepositoryMockGetByUserID {
	if mmGetByUserID.mock.funcGetByUserID != nil {
		mmGetByUserID.mock.t.Fatalf("ConversationRepositoryMock.GetByUserID mock is already set by Set")
	}

	if mmGetByUserID.defaultExpectation == nil {
		mmGetByUserID.defaultExpectation = &ConversationRepositoryMockGetByUserIDExpectation{}
	}

	if mmGetByUserID.defaultExpectation.params != nil {
		mmGetByUserID.mock.t.Fatalf("ConversationRepositoryMock.GetByUserID mock is already set by Expect")
	}

	if mmGetByUserID.defaultExpectation.paramPtrs == nil {
		mmGetByUserID.defaultExpectation.paramPtrs = &ConversationRepositoryMockGetByUserIDParamPtrs{}
	}
	mmGetByUserID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByUserID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByUserID
}

// ExpectUserIDParam2 sets up expected param userID for ConversationRepository.GetByUserID
func (mmGetByUserID *mConversationRepositoryMockGetByUserID) ExpectUserIDParam2(userID string) *mConversationRepositoryMockGetByUserID {
	if mmGetByUserID.mock.funcGetByUserID != nil {
		mmGetByUserID.mock.t.Fatalf("ConversationRepositoryMock.GetByUserID mock is already set by Set")
	}

	if mmGetByUserID.defaultExpectation == nil {
		mmGetByUserID.defaultExpectation = &ConversationRepositoryMockGetByUserIDExpectation{}
	}

	if mmGetByUserID.defaultExpectation.params != nil {
		mmGetByUserID.mock.t.Fatalf("ConversationRepositoryMock.GetByUserID mock is already set by Expect")
	}

	if mmGetByUserID.defaultExpectation.paramPtrs == nil {
		mmGetByUserID.defaultExpectation.paramPtrs = &ConversationRepositoryMockGetByUserIDParamPtrs{}
	}
	mmGetByUserID.defaultExpectation.paramPtrs.userID = &userID
	mmGetByUserID.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmGetByUserID
}

// Inspect accepts an inspector function that has same arguments as the ConversationRepository.GetByUserID
func (mmGetByUserID *mConversationRepositoryMockGetByUserID) Inspect(f func(ctx context.Context, userID string)) *mConversationRepositoryMockGetByUserID {
	if mmGetByUserID.mock.inspectFuncGetByUserID != nil {
		mmGetByUserID.mock.t.Fatalf("Inspect function is already set for ConversationRepositoryMock.GetByUserID")
	}

	mmGetByUserID.mock.inspectFuncGetByUserID = f

	return mmGetByUserID
}

// Return sets up results that will be returned by ConversationRepository.GetByUserID
func (mmGetByUserID *mConversationRepositoryMockGetByUserID) Return(ca1 []models.Conversation, err error) *ConversationRepositoryMock {
	if mmGetByUserID.mock.funcGetByUserID != nil {
		mmGetByUserID.mock.t.Fatalf("ConversationRepositoryMock.GetByUserID mock is already set by Set")
	}

	if mmGetByUserID.defaultExpectation == nil {
		mmGetByUserID.defaultExpectation = &ConversationRepositoryMockGetByUserIDExpectation{mock: mmGetByUserID.mock}
	}
	mmGetByUserID.defaultExpectation.results = &ConversationRepositoryMockGetByUserIDResults{ca1, err}
	mmGetByUserID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByUserID.mock
}

// Set uses given function f to mock the ConversationRepository.GetByUserID method
func (mmGetByUserID *mConversationRepositoryMockGetByUserID) Set(f func(ctx context.Context, userID string) (ca1 []models.Conversation, err error)) *ConversationRepositoryMock {
	if mmGetByUserID.defaultExpectation != nil {
		mmGetByUserID.mock.t.Fatalf("Default expectation is already set for the ConversationRepository.GetByUserID method")
	}

	if len(mmGetByUserID.expectations) > 0 {
		mmGetByUserID.mock.t.Fatalf("Some expectations are already set for the ConversationRepository.GetByUserID method")
	}

	mmGetByUserID.mock.funcGetByUserID = f
	mmGetByUserID.mock.funcGetByUserIDOrigin = minimock.CallerInfo(1)
	return mmGetByUserID.mock
}

// When sets expectation for the ConversationRepository.GetByUserID which will trigger the result defined by the following
// Then helper
func (mmGetByUserID *mConversationRepositoryMockGetByUserID) When(ctx context.Context, userID string) *ConversationRepositoryMockGetByUserIDExpectation {
	if mmGetByUserID.mock.funcGetByUserID != nil {
		mmGetByUserID.mock.t.Fatalf("ConversationRepositoryMock.GetByUserID mock is already set by Set")
	}

	expectation := &ConversationRepositoryMockGetByUserIDExpectation{
		mock:               mmGetByUserID.mock,
		params:             &ConversationRepositoryMockGetByUserIDParams{ctx, userID},
		expectationOrigins: ConversationRepositoryMockGetByUserIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByUserID.expectations = append(mmGetByUserID.expectations, expectation)
	return expectation
}

// Then sets up ConversationRepository.GetByUserID return parameters for the expectation previously defined by the When method
func (e *ConversationRepositoryMockGetByUserIDExpectation) Then(ca1 []models.Conversation, err error) *ConversationRepositoryMock {
	e.results = &ConversationRepositoryMockGetByUserIDResults{ca1, err}
	return e.mock
}

// Times sets number of times ConversationRepository.GetByUserID should be invoked
func (mmGetByUserID *mConversationRepositoryMockGetByUserID) Times(n uint64) *mConversationRepositoryMockGetByUserID {
	if n == 0 {
		mmGetByUserID.mock.t.Fatalf("Times of ConversationRepositoryMock.GetByUserID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByUserID.expectedInvocations, n)
	mmGetByUserID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByUserID
}

func (mmGetByUserID *mConversationRepositoryMockGetByUserID) invocationsDone() bool {
	if len(mmGetByUserID.expectations) == 0 && mmGetByUserID.defaultExpectation == nil && mmGetByUserID.mock.funcGetByUserID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByUserID.mock.afterGetByUserIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByUserID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByUserID implements mm_repository.ConversationRepository
func (mmGetByUserID *ConversationRepositoryMock) GetByUserID(ctx context.Context, userID string) (ca1 []models.Conversation, err error) {
	mm_atomic.AddUint64(&mmGetByUserID.beforeGetByUserIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByUserID.afterGetByUserIDCounter, 1)

	mmGetByUserID.t.Helper()

	if mmGetByUserID.inspectFuncGetByUserID != nil {
		mmGetByUserID.inspectFuncGetByUserID(ctx, userID)
	}

	mm_params := ConversationRepositoryMockGetByUserIDParams{ctx, userID}

	// Record call args
	mmGetByUserID.GetByUserIDMock.mutex.Lock()
	mmGetByUserID.GetByUserIDMock.callArgs = append(mmGetByUserID.GetByUserIDMock.callArgs, &mm_params)
	mmGetByUserID.GetByUserIDMock.mutex.Unlock()

	for _, e := range mmGetByUserID.GetByUserIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ca1, e.results.err
		}
	}

	if mmGetByUserID.GetByUserIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByUserID.GetByUserIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByUserID.GetByUserIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByUserID.GetByUserIDMock.defaultExpectation.paramPtrs

		mm_got := ConversationRepositoryMockGetByUserIDParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByUserID.t.Errorf("ConversationRepositoryMock.GetByUserID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByUserID.GetByUserIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetByUserID.t.Errorf("ConversationRepositoryMock.GetByUserID got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByUserID.GetByUserIDMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByUserID.t.Errorf("ConversationRepositoryMock.GetByUserID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByUserID.GetByUserIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByUserID.GetByUserIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByUserID.t.Fatal("No results are set for the ConversationRepositoryMock.GetByUserID")
		}
		return (*mm_results).ca1, (*mm_results).err
	}
	if mmGetByUserID.funcGetByUserID != nil {
		return mmGetByUserID.funcGetByUserID(ctx, userID)
	}
	mmGetByUserID.t.Fatalf("Unexpected call to ConversationRepositoryMock.GetByUserID. %v %v", ctx, userID)
	return
}

// GetByUserIDAfterCounter returns a count of finished ConversationRepositoryMock.GetByUserID invocations
func (mmGetByUserID *ConversationRepositoryMock) GetByUserIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByUserID.afterGetByUserIDCounter)
}

// GetByUserIDBeforeCounter returns a count of ConversationRepositoryMock.GetByUserID invocations
func (mmGetByUserID *ConversationRepositoryMock) GetByUserIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByUserID.beforeGetByUserIDCounter)
}

// Calls returns a list of arguments used in each call to ConversationRepositoryMock.GetByUserID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByUserID *mConversationRepositoryMockGetByUserID) Calls() []*ConversationRepositoryMockGetByUserIDParams {
	mmGetByUserID.mutex.RLock()

	argCopy := make([]*ConversationRepositoryMockGetByUserIDParams, len(mmGetByUserID.callArgs))
	copy(argCopy, mmGetByUserID.callArgs)

	mmGetByUserID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByUserIDDone returns true if the count of the GetByUserID invocations corresponds
// the number of defined expectations
func (m *ConversationRepositoryMock) MinimockGetByUserIDDone() bool {
	if m.GetByUserIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByUserIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByUserIDMock.invocationsDone()
}

// MinimockGetByUserIDInspect logs each unmet expectation
func (m *ConversationRepositoryMock) MinimockGetByUserIDInspect() {
	for _, e := range m.GetByUserIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ConversationRepositoryMock.GetByUserID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByUserIDCounter := mm_atomic.LoadUint64(&m.afterGetByUserIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByUserIDMock.defaultExpectation != nil && afterGetByUserIDCounter < 1 {
		if m.GetByUserIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ConversationRepositoryMock.GetByUserID at\n%s", m.GetByUserIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ConversationRepositoryMock.GetByUserID at\n%s with params: %#v", m.GetByUserIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByUserIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByUserID != nil && afterGetByUserIDCounter < 1 {
		m.t.Errorf("Expected call to ConversationRepositoryMock.GetByUserID at\n%s", m.funcGetByUserIDOrigin)
	}

	if !m.GetByUserIDMock.invocationsDone() && afterGetByUserIDCounter > 0 {
		m.t.Errorf("Expected %d calls to ConversationRepositoryMock.GetByUserID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByUserIDMock.expectedInvocations), m.GetByUserIDMock.expectedInvocationsOrigin, afterGetByUserIDCounter)
	}
}

type mConversationRepositoryMockGetOrCreate struct {
	optional           bool
	mock               *ConversationRepositoryMock
	defaultExpectation *ConversationRepositoryMockGetOrCreateExpectation
	expectations       []*ConversationRepositoryMockGetOrCreateExpectation

	callArgs []*ConversationRepositoryMockGetOrCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ConversationRepositoryMockGetOrCreateExpectation specifies expectation struct of the ConversationRepository.GetOrCreate
type ConversationRepositoryMockGetOrCreateExpectation struct {
	mock               *ConversationRepositoryMock
	params             *ConversationRepositoryMockGetOrCreateParams
	paramPtrs          *ConversationRepositoryMockGetOrCreateParamPtrs
	expectationOrigins ConversationRepositoryMockGetOrCreateExpectationOrigins
	results            *ConversationRepositoryMockGetOrCreateResults
	returnOrigin       string
	Counter            uint64
}

// ConversationRepositoryMockGetOrCreateParams contains parameters of the ConversationRepository.GetOrCreate
type ConversationRepositoryMockGetOrCreateParams struct {
	ctx     context.Context
	userAID string
	userBID string
}

// ConversationRepositoryMockGetOrCreateParamPtrs contains pointers to parameters of the ConversationRepository.GetOrCreate
type ConversationRepositoryMockGetOrCreateParamPtrs struct {
	ctx     *context.Context
	userAID *string
	userBID *string
}

// ConversationRepositoryMockGetOrCreateResults contains results of the ConversationRepository.GetOrCreate
type ConversationRepositoryMockGetOrCreateResults struct {
	cp1 *models.Conversation
	err error
}

// ConversationRepositoryMockGetOrCreateOrigins contains origins of expectations of the ConversationRepository.GetOrCreate
type ConversationRepositoryMockGetOrCreateExpectationOrigins struct {
	origin        string
	originCtx     string
	originUserAID string
	originUserBID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) Optional() *mConversationRepositoryMockGetOrCreate {
	mmGetOrCreate.optional = true
	return mmGetOrCreate
}

// Expect sets up expected params for ConversationRepository.GetOrCreate
func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) Expect(ctx context.Context, userAID string, userBID string) *mConversationRepositoryMockGetOrCreate {
	if mmGetOrCreate.mock.funcGetOrCreate != nil {
		mmGetOrCreate.mock.t.Fatalf("ConversationRepositoryMock.GetOrCreate mock is already set by Set")
	}

	if mmGetOrCreate.defaultExpectation == nil {
		mmGetOrCreate.defaultExpectation = &ConversationRepositoryMockGetOrCreateExpectation{}
	}

	if mmGetOrCreate.defaultExpectation.paramPtrs != nil {
		mmGetOrCreate.mock.t.Fatalf("ConversationRepositoryMock.GetOrCreate mock is already set by ExpectParams functions")
	}

	mmGetOrCreate.defaultExpectation.params = &ConversationRepositoryMockGetOrCreateParams{ctx, userAID, userBID}
	mmGetOrCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetOrCreate.expectations {
		if minimock.Equal(e.params, mmGetOrCreate.defaultExpectation.params) {
			mmGetOrCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetOrCreate.defaultExpectation.params)
		}
	}

	return mmGetOrCreate
}

// ExpectCtxParam1 sets up expected param ctx for ConversationRepository.GetOrCreate
func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) ExpectCtxParam1(ctx context.Context) *mConversationRepositoryMockGetOrCreate {
	if mmGetOrCreate.mock.funcGetOrCreate != nil {
		mmGetOrCreate.mock.t.Fatalf("ConversationRepositoryMock.GetOrCreate mock is already set by Set")
	}

	if mmGetOrCreate.defaultExpectation == nil {
		mmGetOrCreate.defaultExpectation = &ConversationRepositoryMockGetOrCreateExpectation{}
	}

	if mmGetOrCreate.defaultExpectation.params != nil {
		mmGetOrCreate.mock.t.Fatalf("ConversationRepositoryMock.GetOrCreate mock is already set by Expect")
	}

	if mmGetOrCreate.defaultExpectation.paramPtrs == nil {
		mmGetOrCreate.defaultExpectation.paramPtrs = &ConversationRepositoryMockGetOrCreateParamPtrs{}
	}
	mmGetOrCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetOrCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetOrCreate
}

// ExpectUserAIDParam2 sets up expected param userAID for ConversationRepository.GetOrCreate
func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) ExpectUserAIDParam2(userAID string) *mConversationRepositoryMockGetOrCreate {
	if mmGetOrCreate.mock.funcGetOrCreate != nil {
		mmGetOrCreate.mock.t.Fatalf("ConversationRepositoryMock.GetOrCreate mock is already set by Set")
	}

	if mmGetOrCreate.defaultExpectation == nil {
		mmGetOrCreate.defaultExpectation = &ConversationRepositoryMockGetOrCreateExpectation{}
	}

	if mmGetOrCreate.defaultExpectation.params != nil {
		mmGetOrCreate.mock.t.Fatalf("ConversationRepositoryMock.GetOrCreate mock is already set by Expect")
	}

	if mmGetOrCreate.defaultExpectation.paramPtrs == nil {
		mmGetOrCreate.defaultExpectation.paramPtrs = &ConversationRepositoryMockGetOrCreateParamPtrs{}
	}
	mmGetOrCreate.defaultExpectation.paramPtrs.userAID = &userAID
	mmGetOrCreate.defaultExpectation.expectationOrigins.originUserAID = minimock.CallerInfo(1)

	return mmGetOrCreate
}

// ExpectUserBIDParam3 sets up expected param userBID for ConversationRepository.GetOrCreate
func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) ExpectUserBIDParam3(userBID string) *mConversationRepositoryMockGetOrCreate {
	if mmGetOrCreate.mock.funcGetOrCreate != nil {
		mmGetOrCreate.mock.t.Fatalf("ConversationRepositoryMock.GetOrCreate mock is already set by Set")
	}

	if mmGetOrCreate.defaultExpectation == nil {
		mmGetOrCreate.defaultExpectation = &ConversationRepositoryMockGetOrCreateExpectation{}
	}

	if mmGetOrCreate.defaultExpectation.params != nil {
		mmGetOrCreate.mock.t.Fatalf("ConversationRepositoryMock.GetOrCreate mock is already set by Expect")
	}

	if mmGetOrCreate.defaultExpectation.paramPtrs == nil {
		mmGetOrCreate.defaultExpectation.paramPtrs = &ConversationRepositoryMockGetOrCreateParamPtrs{}
	}
	mmGetOrCreate.defaultExpectation.paramPtrs.userBID = &userBID
	mmGetOrCreate.defaultExpectation.expectationOrigins.originUserBID = minimock.CallerInfo(1)

	return mmGetOrCreate
}

// Inspect accepts an inspector function that has same arguments as the ConversationRepository.GetOrCreate
func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) Inspect(f func(ctx context.Context, userAID string, userBID string)) *mConversationRepositoryMockGetOrCreate {
	if mmGetOrCreate.mock.inspectFuncGetOrCreate != nil {
		mmGetOrCreate.mock.t.Fatalf("Inspect function is already set for ConversationRepositoryMock.GetOrCreate")
	}

	mmGetOrCreate.mock.inspectFuncGetOrCreate = f

	return mmGetOrCreate
}

// Return sets up results that will be returned by ConversationRepository.GetOrCreate
func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) Return(cp1 *models.Conversation, err error) *ConversationRepositoryMock {
	if mmGetOrCreate.mock.funcGetOrCreate != nil {
		mmGetOrCreate.mock.t.Fatalf("ConversationRepositoryMock.GetOrCreate mock is already set by Set")
	}

	if mmGetOrCreate.defaultExpectation == nil {
		mmGetOrCreate.defaultExpectation = &ConversationRepositoryMockGetOrCreateExpectation{mock: mmGetOrCreate.mock}
	}
	mmGetOrCreate.defaultExpectation.results = &ConversationRepositoryMockGetOrCreateResults{cp1, err}
	mmGetOrCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetOrCreate.mock
}

// Set uses given function f to mock the ConversationRepository.GetOrCreate method
func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) Set(f func(ctx context.Context, userAID string, userBID string) (cp1 *models.Conversation, err error)) *ConversationRepositoryMock {
	if mmGetOrCreate.defaultExpectation != nil {
		mmGetOrCreate.mock.t.Fatalf("Default expectation is already set for the ConversationRepository.GetOrCreate method")
	}

	if len(mmGetOrCreate.expectations) > 0 {
		mmGetOrCreate.mock.t.Fatalf("Some expectations are already set for the ConversationRepository.GetOrCreate method")
	}

	mmGetOrCreate.mock.funcGetOrCreate = f
	mmGetOrCreate.mock.funcGetOrCreateOrigin = minimock.CallerInfo(1)
	return mmGetOrCreate.mock
}

// When sets expectation for the ConversationRepository.GetOrCreate which will trigger the result defined by the following
// Then helper
func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) When(ctx context.Context, userAID string, userBID string) *ConversationRepositoryMockGetOrCreateExpectation {
	if mmGetOrCreate.mock.funcGetOrCreate != nil {
		mmGetOrCreate.mock.t.Fatalf("ConversationRepositoryMock.GetOrCreate mock is already set by Set")
	}

	expectation := &ConversationRepositoryMockGetOrCreateExpectation{
		mock:               mmGetOrCreate.mock,
		params:             &ConversationRepositoryMockGetOrCreateParams{ctx, userAID, userBID},
		expectationOrigins: ConversationRepositoryMockGetOrCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetOrCreate.expectations = append(mmGetOrCreate.expectations, expectation)
	return expectation
}

// Then sets up ConversationRepository.GetOrCreate return parameters for the expectation previously defined by the When method
func (e *ConversationRepositoryMockGetOrCreateExpectation) Then(cp1 *models.Conversation, err error) *ConversationRepositoryMock {
	e.results = &ConversationRepositoryMockGetOrCreateResults{cp1, err}
	return e.mock
}

// Times sets number of times ConversationRepository.GetOrCreate should be invoked
func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) Times(n uint64) *mConversationRepositoryMockGetOrCreate {
	if n == 0 {
		mmGetOrCreate.mock.t.Fatalf("Times of ConversationRepositoryMock.GetOrCreate mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetOrCreate.expectedInvocations, n)
	mmGetOrCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetOrCreate
}

func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) invocationsDone() bool {
	if len(mmGetOrCreate.expectations) == 0 && mmGetOrCreate.defaultExpectation == nil && mmGetOrCreate.mock.funcGetOrCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetOrCreate.mock.afterGetOrCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetOrCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetOrCreate implements mm_repository.ConversationRepository
func (mmGetOrCreate *ConversationRepositoryMock) GetOrCreate(ctx context.Context, userAID string, userBID string) (cp1 *models.Conversation, err error) {
	mm_atomic.AddUint64(&mmGetOrCreate.beforeGetOrCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmGetOrCreate.afterGetOrCreateCounter, 1)

	mmGetOrCreate.t.Helper()

	if mmGetOrCreate.inspectFuncGetOrCreate != nil {
		mmGetOrCreate.inspectFuncGetOrCreate(ctx, userAID, userBID)
	}

	mm_params := ConversationRepositoryMockGetOrCreateParams{ctx, userAID, userBID}

	// Record call args
	mmGetOrCreate.GetOrCreateMock.mutex.Lock()
	mmGetOrCreate.GetOrCreateMock.callArgs = append(mmGetOrCreate.GetOrCreateMock.callArgs, &mm_params)
	mmGetOrCreate.GetOrCreateMock.mutex.Unlock()

	for _, e := range mmGetOrCreate.GetOrCreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmGetOrCreate.GetOrCreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetOrCreate.GetOrCreateMock.defaultExpectation.Counter, 1)
		mm_want := mmGetOrCreate.GetOrCreateMock.defaultExpectation.params
		mm_want_ptrs := mmGetOrCreate.GetOrCreateMock.defaultExpectation.paramPtrs

		mm_got := ConversationRepositoryMockGetOrCreateParams{ctx, userAID, userBID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetOrCreate.t.Errorf("ConversationRepositoryMock.GetOrCreate got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetOrCreate.GetOrCreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userAID != nil && !minimock.Equal(*mm_want_ptrs.userAID, mm_got.userAID) {
				mmGetOrCreate.t.Errorf("ConversationRepositoryMock.GetOrCreate got unexpected parameter userAID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetOrCreate.GetOrCreateMock.defaultExpectation.expectationOrigins.originUserAID, *mm_want_ptrs.userAID, mm_got.userAID, minimock.Diff(*mm_want_ptrs.userAID, mm_got.userAID))
			}

			if mm_want_ptrs.userBID != nil && !minimock.Equal(*mm_want_ptrs.userBID, mm_got.userBID) {
				mmGetOrCreate.t.Errorf("ConversationRepositoryMock.GetOrCreate got unexpected parameter userBID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetOrCreate.GetOrCreateMock.defaultExpectation.expectationOrigins.originUserBID, *mm_want_ptrs.userBID, mm_got.userBID, minimock.Diff(*mm_want_ptrs.userBID, mm_got.userBID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetOrCreate.t.Errorf("ConversationRepositoryMock.GetOrCreate got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetOrCreate.GetOrCreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetOrCreate.GetOrCreateMock.defaultExpectation.results
		if mm_results == nil {
			mmGetOrCreate.t.Fatal("No results are set for the ConversationRepositoryMock.GetOrCreate")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmGetOrCreate.funcGetOrCreate != nil {
		return mmGetOrCreate.funcGetOrCreate(ctx, userAID, userBID)
	}
	mmGetOrCreate.t.Fatalf("Unexpected call to ConversationRepositoryMock.GetOrCreate. %v %v %v", ctx, userAID, userBID)
	return
}

// GetOrCreateAfterCounter returns a count of finished ConversationRepositoryMock.GetOrCreate invocations
func (mmGetOrCreate *ConversationRepositoryMock) GetOrCreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetOrCreate.afterGetOrCreateCounter)
}

// GetOrCreateBeforeCounter returns a count of ConversationRepositoryMock.GetOrCreate invocations
func (mmGetOrCreate *ConversationRepositoryMock) GetOrCreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetOrCreate.beforeGetOrCreateCounter)
}

// Calls returns a list of arguments used in each call to ConversationRepositoryMock.GetOrCreate.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetOrCreate *mConversationRepositoryMockGetOrCreate) Calls() []*ConversationRepositoryMockGetOrCreateParams {
	mmGetOrCreate.mutex.RLock()

	argCopy := make([]*ConversationRepositoryMockGetOrCreateParams, len(mmGetOrCreate.callArgs))
	copy(argCopy, mmGetOrCreate.callArgs)

	mmGetOrCreate.mutex.RUnlock()

	return argCopy
}

// MinimockGetOrCreateDone returns true if the count of the GetOrCreate invocations corresponds
// the number of defined expectations
func (m *ConversationRepositoryMock) MinimockGetOrCreateDone() bool {
	if m.GetOrCreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetOrCreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetOrCreateMock.invocationsDone()
}

// MinimockGetOrCreateInspect logs each unmet expectation
func (m *ConversationRepositoryMock) MinimockGetOrCreateInspect() {
	for _, e := range m.GetOrCreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ConversationRepositoryMock.GetOrCreate at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetOrCreateCounter := mm_atomic.LoadUint64(&m.afterGetOrCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetOrCreateMock.defaultExpectation != nil && afterGetOrCreateCounter < 1 {
		if m.GetOrCreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ConversationRepositoryMock.GetOrCreate at\n%s", m.GetOrCreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ConversationRepositoryMock.GetOrCreate at\n%s with params: %#v", m.GetOrCreateMock.defaultExpectation.expectationOrigins.origin, *m.GetOrCreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetOrCreate != nil && afterGetOrCreateCounter < 1 {
		m.t.Errorf("Expected call to ConversationRepositoryMock.GetOrCreate at\n%s", m.funcGetOrCreateOrigin)
	}

	if !m.GetOrCreateMock.invocationsDone() && afterGetOrCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to ConversationRepositoryMock.GetOrCreate at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetOrCreateMock.expectedInvocations), m.GetOrCreateMock.expectedInvocationsOrigin, afterGetOrCreateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ConversationRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetByIDInspect()

			m.MinimockGetByUserIDInspect()

			m.MinimockGetOrCreateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ConversationRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ConversationRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetByIDDone() &&
		m.MinimockGetByUserIDDone() &&
		m.MinimockGetOrCreateDone()
}
