// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i app/internal/repository.MessageRepository -o message_repo_mock.go -n MessageRepositoryMock -p mocks

import (
	"app/internal/models"
	"context"
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// MessageRepositoryMock implements mm_repository.MessageRepository
type MessageRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, conversationID string, senderID string, ciphertext string, nonce string) (mp1 *models.Message, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, conversationID string, senderID string, ciphertext string, nonce string)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mMessageRepositoryMockCreate

	funcGetByConversationID          func(ctx context.Context, conversationID string) (ma1 []models.Message, err error)
	funcGetByConversationIDOrigin    string
	inspectFuncGetByConversationID   func(ctx context.Context, conversationID string)
	afterGetByConversationIDCounter  uint64
	beforeGetByConversationIDCounter uint64
	GetByConversationIDMock          mMessageRepositoryMockGetByConversationID

	funcGetPublic          func(ctx context.Context, limit int, before *time.Time) (pa1 []models.PublicMessage, err error)
	funcGetPublicOrigin    string
	inspectFuncGetPublic   func(ctx context.Context, limit int, before *time.Time)
	afterGetPublicCounter  uint64
	beforeGetPublicCounter uint64
	GetPublicMock          mMessageRepositoryMockGetPublic
}

// NewMessageRepositoryMock returns a mock for mm_repository.MessageRepository
func NewMessageRepositoryMock(t minimock.Tester) *MessageRepositoryMock {
	m := &MessageRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mMessageRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*MessageRepositoryMockCreateParams{}

	m.GetByConversationIDMock = mMessageRepositoryMockGetByConversationID{mock: m}
	m.GetByConversationIDMock.callArgs = []*MessageRepositoryMockGetByConversationIDParams{}

	m.GetPublicMock = mMessageRepositoryMockGetPublic{mock: m}
	m.GetPublicMock.callArgs = []*MessageRepositoryMockGetPublicParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mMessageRepositoryMockCreate struct {
	optional           bool
	mock               *MessageRepositoryMock
	defaultExpectation *MessageRepositoryMockCreateExpectation
	expectations       []*MessageRepositoryMockCreateExpectation

	callArgs []*MessageRepositoryMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MessageRepositoryMockCreateExpectation specifies expectation struct of the MessageRepository.Create
type MessageRepositoryMockCreateExpectation struct {
	mock               *MessageRepositoryMock
	params             *MessageRepositoryMockCreateParams
	paramPtrs          *MessageRepositoryMockCreateParamPtrs
	expectationOrigins MessageRepositoryMockCreateExpectationOrigins
	results            *MessageRepositoryMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// MessageRepositoryMockCreateParams contains parameters of the MessageRepository.Create
type MessageRepositoryMockCreateParams struct {
	ctx            context.Context
	conversationID string
	senderID       string
	ciphertext     string
	nonce          string
}

// MessageRepositoryMockCreateParamPtrs contains pointers to parameters of the MessageRepository.Create
type MessageRepositoryMockCreateParamPtrs struct {
	ctx            *context.Context
	conversationID *string
	senderID       *string
	ciphertext     *string
	nonce          *string
}

// MessageRepositoryMockCreateResults contains results of the MessageRepository.Create
type MessageRepositoryMockCreateResults struct {
	mp1 *models.Message
	err error
}

// MessageRepositoryMockCreateOrigins contains origins of expectations of the MessageRepository.Create
type MessageRepositoryMockCreateExpectationOrigins struct {
	origin               string
	originCtx            string
	originConversationID string
	originSenderID       string
	originCiphertext     string
	originNonce          string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mMessageRepositoryMockCreate) Optional() *mMessageRepositoryMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) Expect(ctx context.Context, conversationID string, senderID string, ciphertext string, nonce string) *mMessageRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &MessageRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &MessageRepositoryMockCreateParams{ctx, conversationID, senderID, ciphertext, nonce}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) ExpectCtxParam1(ctx context.Context) *mMessageRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &MessageRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &MessageRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectConversationIDParam2 sets up expected param conversationID for MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) ExpectConversationIDParam2(conversationID string) *mMessageRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &MessageRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &MessageRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.conversationID = &conversationID
	mmCreate.defaultExpectation.expectationOrigins.originConversationID = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectSenderIDParam3 sets up expected param senderID for MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) ExpectSenderIDParam3(senderID string) *mMessageRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &MessageRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &MessageRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.senderID = &senderID
	mmCreate.defaultExpectation.expectationOrigins.originSenderID = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectCiphertextParam4 sets up expected param ciphertext for MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) ExpectCiphertextParam4(ciphertext string) *mMessageRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &MessageRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &MessageRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ciphertext = &ciphertext
	mmCreate.defaultExpectation.expectationOrigins.originCiphertext = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectNonceParam5 sets up expected param nonce for MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) ExpectNonceParam5(nonce string) *mMessageRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &MessageRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &MessageRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.nonce = &nonce
	mmCreate.defaultExpectation.expectationOrigins.originNonce = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) Inspect(f func(ctx context.Context, conversationID string, senderID string, ciphertext string, nonce string)) *mMessageRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for MessageRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by MessageRepository.Create
func (mmCreate *mMessageRepositoryMockCreate) Return(mp1 *models.Message, err error) *MessageRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &MessageRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &MessageRepositoryMockCreateResults{mp1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the MessageRepository.Create method
func (mmCreate *mMessageRepositoryMockCreate) Set(f func(ctx context.Context, conversationID string, senderID string, ciphertext string, nonce string) (mp1 *models.Message, err error)) *MessageRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the MessageRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the MessageRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the MessageRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mMessageRepositoryMockCreate) When(ctx context.Context, conversationID string, senderID string, ciphertext string, nonce string) *MessageRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("MessageRepositoryMock.Create mock is already set by Set")
	}

	expectation := &MessageRepositoryMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &MessageRepositoryMockCreateParams{ctx, conversationID, senderID, ciphertext, nonce},
		expectationOrigins: MessageRepositoryMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up MessageRepository.Create return parameters for the expectation previously defined by the When method
func (e *MessageRepositoryMockCreateExpectation) Then(mp1 *models.Message, err error) *MessageRepositoryMock {
	e.results = &MessageRepositoryMockCreateResults{mp1, err}
	return e.mock
}

// Times sets number of times MessageRepository.Create should be invoked
func (mmCreate *mMessageRepositoryMockCreate) Times(n uint64) *mMessageRepositoryMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of MessageRepositoryMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mMessageRepositoryMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_repository.MessageRepository
func (mmCreate *MessageRepositoryMock) Create(ctx context.Context, conversationID string, senderID string, ciphertext string, nonce string) (mp1 *models.Message, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, conversationID, senderID, ciphertext, nonce)
	}

	mm_params := MessageRepositoryMockCreateParams{ctx, conversationID, senderID, ciphertext, nonce}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.mp1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := MessageRepositoryMockCreateParams{ctx, conversationID, senderID, ciphertext, nonce}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("MessageRepositoryMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.conversationID != nil && !minimock.Equal(*mm_want_ptrs.conversationID, mm_got.conversationID) {
				mmCreate.t.Errorf("MessageRepositoryMock.Create got unexpected parameter conversationID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originConversationID, *mm_want_ptrs.conversationID, mm_got.conversationID, minimock.Diff(*mm_want_ptrs.conversationID, mm_got.conversationID))
			}

			if mm_want_ptrs.senderID != nil && !minimock.Equal(*mm_want_ptrs.senderID, mm_got.senderID) {
				mmCreate.t.Errorf("MessageRepositoryMock.Create got unexpected parameter senderID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originSenderID, *mm_want_ptrs.senderID, mm_got.senderID, minimock.Diff(*mm_want_ptrs.senderID, mm_got.senderID))
			}

			if mm_want_ptrs.ciphertext != nil && !minimock.Equal(*mm_want_ptrs.ciphertext, mm_got.ciphertext) {
				mmCreate.t.Errorf("MessageRepositoryMock.Create got unexpected parameter ciphertext, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCiphertext, *mm_want_ptrs.ciphertext, mm_got.ciphertext, minimock.Diff(*mm_want_ptrs.ciphertext, mm_got.ciphertext))
			}

			if mm_want_ptrs.nonce != nil && !minimock.Equal(*mm_want_ptrs.nonce, mm_got.nonce) {
				mmCreate.t.Errorf("MessageRepositoryMock.Create got unexpected parameter nonce, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originNonce, *mm_want_ptrs.nonce, mm_got.nonce, minimock.Diff(*mm_want_ptrs.nonce, mm_got.nonce))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("MessageRepositoryMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the MessageRepositoryMock.Create")
		}
		return (*mm_results).mp1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, conversationID, senderID, ciphertext, nonce)
	}
	mmCreate.t.Fatalf("Unexpected call to MessageRepositoryMock.Create. %v %v %v %v %v", ctx, conversationID, senderID, ciphertext, nonce)
	return
}

// CreateAfterCounter returns a count of finished MessageRepositoryMock.Create invocations
func (mmCreate *MessageRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of MessageRepositoryMock.Create invocations
func (mmCreate *MessageRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to MessageRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mMessageRepositoryMockCreate) Calls() []*MessageRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*MessageRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *MessageRepositoryMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *MessageRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MessageRepositoryMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MessageRepositoryMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MessageRepositoryMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to MessageRepositoryMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to MessageRepositoryMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mMessageRepositoryMockGetByConversationID struct {
	optional           bool
	mock               *MessageRepositoryMock
	defaultExpectation *MessageRepositoryMockGetByConversationIDExpectation
	expectations       []*MessageRepositoryMockGetByConversationIDExpectation

	callArgs []*MessageRepositoryMockGetByConversationIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MessageRepositoryMockGetByConversationIDExpectation specifies expectation struct of the MessageRepository.GetByConversationID
type MessageRepositoryMockGetByConversationIDExpectation struct {
	mock               *MessageRepositoryMock
	params             *MessageRepositoryMockGetByConversationIDParams
	paramPtrs          *MessageRepositoryMockGetByConversationIDParamPtrs
	expectationOrigins MessageRepositoryMockGetByConversationIDExpectationOrigins
	results            *MessageRepositoryMockGetByConversationIDResults
	returnOrigin       string
	Counter            uint64
}

// MessageRepositoryMockGetByConversationIDParams contains parameters of the MessageRepository.GetByConversationID
type MessageRepositoryMockGetByConversationIDParams struct {
	ctx            context.Context
	conversationID string
}

// MessageRepositoryMockGetByConversationIDParamPtrs contains pointers to parameters of the MessageRepository.GetByConversationID
type MessageRepositoryMockGetByConversationIDParamPtrs struct {
	ctx            *context.Context
	conversationID *string
}

// MessageRepositoryMockGetByConversationIDResults contains results of the MessageRepository.GetByConversationID
type MessageRepositoryMockGetByConversationIDResults struct {
	ma1 []models.Message
	err error
}

// MessageRepositoryMockGetByConversationIDOrigins contains origins of expectations of the MessageRepository.GetByConversationID
type MessageRepositoryMockGetByConversationIDExpectationOrigins struct {
	origin               string
	originCtx            string
	originConversationID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByConversationID *mMessageRepositoryMockGetByConversationID) Optional() *mMessageRepositoryMockGetByConversationID {
	mmGetByConversationID.optional = true
	return mmGetByConversationID
}

// Expect sets up expected params for MessageRepository.GetByConversationID
func (mmGetByConversationID *mMessageRepositoryMockGetByConversationID) Expect(ctx context.Context, conversationID string) *mMessageRepositoryMockGetByConversationID {
	if mmGetByConversationID.mock.funcGetByConversationID != nil {
		mmGetByConversationID.mock.t.Fatalf("MessageRepositoryMock.GetByConversationID mock is already set by Set")
	}

	if mmGetByConversationID.defaultExpectation == nil {
		mmGetByConversationID.defaultExpectation = &MessageRepositoryMockGetByConversationIDExpectation{}
	}

	if mmGetByConversationID.defaultExpectation.paramPtrs != nil {
		mmGetByConversationID.mock.t.Fatalf("MessageRepositoryMock.GetByConversationID mock is already set by ExpectParams functions")
	}

	mmGetByConversationID.defaultExpectation.params = &MessageRepositoryMockGetByConversationIDParams{ctx, conversationID}
	mmGetByConversationID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByConversationID.expectations {
		if minimock.Equal(e.params, mmGetByConversationID.defaultExpectation.params) {
			mmGetByConversationID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByConversationID.defaultExpectation.params)
		}
	}

	return mmGetByConversationID
}

// ExpectCtxParam1 sets up expected param ctx for MessageRepository.GetByConversationID
func (mmGetByConversationID *mMessageRepositoryMockGetByConversationID) ExpectCtxParam1(ctx context.Context) *mMessageRepositoryMockGetByConversationID {
	if mmGetByConversationID.mock.funcGetByConversationID != nil {
		mmGetByConversationID.mock.t.Fatalf("MessageRepositoryMock.GetByConversationID mock is already set by Set")
	}

	if mmGetByConversationID.defaultExpectation == nil {
		mmGetByConversationID.defaultExpectation = &MessageRepositoryMockGetByConversationIDExpectation{}
	}

	if mmGetByConversationID.defaultExpectation.params != nil {
		mmGetByConversationID.mock.t.Fatalf("MessageRepositoryMock.GetByConversationID mock is already set by Expect")
	}

	if mmGetByConversationID.defaultExpectation.paramPtrs == nil {
		mmGetByConversationID.defaultExpectation.paramPtrs = &MessageRepositoryMockGetByConversationIDParamPtrs{}
	}
	mmGetByConversationID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByConversationID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByConversationID
}

// ExpectConversationIDParam2 sets up expected param conversationID for MessageRepository.GetByConversationID
func (mmGetByConversationID *mMessageRepositoryMockGetByConversationID) ExpectConversationIDParam2(conversationID string) *mMessageRepositoryMockGetByConversationID {
	if mmGetByConversationID.mock.funcGetByConversationID != nil {
		mmGetByConversationID.mock.t.Fatalf("MessageRepositoryMock.GetByConversationID mock is already set by Set")
	}

	if mmGetByConversationID.defaultExpectation == nil {
		mmGetByConversationID.defaultExpectation = &MessageRepositoryMockGetByConversationIDExpectation{}
	}

	if mmGetByConversationID.defaultExpectation.params != nil {
		mmGetByConversationID.mock.t.Fatalf("MessageRepositoryMock.GetByConversationID mock is already set by Expect")
	}

	if mmGetByConversationID.defaultExpectation.paramPtrs == nil {
		mmGetByConversationID.defaultExpectation.paramPtrs = &MessageRepositoryMockGetByConversationIDParamPtrs{}
	}
	mmGetByConversationID.defaultExpectation.paramPtrs.conversationID = &conversationID
	mmGetByConversationID.defaultExpectation.expectationOrigins.originConversationID = minimock.CallerInfo(1)

	return mmGetByConversationID
}

// Inspect accepts an inspector function that has same arguments as the MessageRepository.GetByConversationID
func (mmGetByConversationID *mMessageRepositoryMockGetByConversationID) Inspect(f func(ctx context.Context, conversationID string)) *mMessageRepositoryMockGetByConversationID {
	if mmGetByConversationID.mock.inspectFuncGetByConversationID != nil {
		mmGetByConversationID.mock.t.Fatalf("Inspect function is already set for MessageRepositoryMock.GetByConversationID")
	}

	mmGetByConversationID.mock.inspectFuncGetByConversationID = f

	return mmGetByConversationID
}

// Return sets up results that will be returned by MessageRepository.GetByConversationID
func (mmGetByConversationID *mMessageRepositoryMockGetByConversationID) Return(ma1 []models.Message, err error) *MessageRepositoryMock {
	if mmGetByConversationID.mock.funcGetByConversationID != nil {
		mmGetByConversationID.mock.t.Fatalf("MessageRepositoryMock.GetByConversationID mock is already set by Set")
	}

	if mmGetByConversationID.defaultExpectation == nil {
		mmGetByConversationID.defaultExpectation = &MessageRepositoryMockGetByConversationIDExpectation{mock: mmGetByConversationID.mock}
	}
	mmGetByConversationID.defaultExpectation.results = &MessageRepositoryMockGetByConversationIDResults{ma1, err}
	mmGetByConversationID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByConversationID.mock
}

// Set uses given function f to mock the MessageRepository.GetByConversationID method
func (mmGetByConversationID *mMessageRepositoryMockGetByConversationID) Set(f func(ctx context.Context, conversationID string) (ma1 []models.Message, err error)) *MessageRepositoryMock {
	if mmGetByConversationID.defaultExpectation != nil {
		mmGetByConversationID.mock.t.Fatalf("Default expectation is already set for the MessageRepository.GetByConversationID method")
	}

	if len(mmGetByConversationID.expectations) > 0 {
		mmGetByConversationID.mock.t.Fatalf("Some expectations are already set for the MessageRepository.GetByConversationID method")
	}

	mmGetByConversationID.mock.funcGetByConversationID = f
	mmGetByConversationID.mock.funcGetByConversationIDOrigin = minimock.CallerInfo(1)
	return mmGetByConversationID.mock
}

// When sets expectation for the MessageRepository.GetByConversationID which will trigger the result defined by the following
// Then helper
func (mmGetByConversationID *mMessageRepositoryMockGetByConversationID) When(ctx context.Context, conversationID string) *MessageRepositoryMockGetByConversationIDExpectation {
	if mmGetByConversationID.mock.funcGetByConversationID != nil {
		mmGetByConversationID.mock.t.Fatalf("MessageRepositoryMock.GetByConversationID mock is already set by Set")
	}

	expectation := &MessageRepositoryMockGetByConversationIDExpectation{
		mock:               mmGetByConversationID.mock,
		params:             &MessageRepositoryMockGetByConversationIDParams{ctx, conversationID},
		expectationOrigins: MessageRepositoryMockGetByConversationIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByConversationID.expectations = append(mmGetByConversationID.expectations, expectation)
	return expectation
}

// Then sets up MessageRepository.GetByConversationID return parameters for the expectation previously defined by the When method
func (e *MessageRepositoryMockGetByConversationIDExpectation) Then(ma1 []models.Message, err error) *MessageRepositoryMock {
	e.results = &MessageRepositoryMockGetByConversationIDResults{ma1, err}
	return e.mock
}

// Times sets number of times MessageRepository.GetByConversationID should be invoked
func (mmGetByConversationID *mMessageRepositoryMockGetByConversationID) Times(n uint64) *mMessageRepositoryMockGetByConversationID {
	if n == 0 {
		mmGetByConversationID.mock.t.Fatalf("Times of MessageRepositoryMock.GetByConversationID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByConversationID.expectedInvocations, n)
	mmGetByConversationID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByConversationID
}

func (mmGetByConversationID *mMessageRepositoryMockGetByConversationID) invocationsDone() bool {
	if len(mmGetByConversationID.expectations) == 0 && mmGetByConversationID.defaultExpectation == nil && mmGetByConversationID.mock.funcGetByConversationID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByConversationID.mock.afterGetByConversationIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByConversationID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByConversationID implements mm_repository.MessageRepository
func (mmGetByConversationID *MessageRepositoryMock) GetByConversationID(ctx context.Context, conversationID string) (ma1 []models.Message, err error) {
	mm_atomic.AddUint64(&mmGetByConversationID.beforeGetByConversationIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByConversationID.afterGetByConversationIDCounter, 1)

	mmGetByConversationID.t.Helper()

	if mmGetByConversationID.inspectFuncGetByConversationID != nil {
		mmGetByConversationID.inspectFuncGetByConversationID(ctx, conversationID)
	}

	mm_params := MessageRepositoryMockGetByConversationIDParams{ctx, conversationID}

	// Record call args
	mmGetByConversationID.GetByConversationIDMock.mutex.Lock()
	mmGetByConversationID.GetByConversationIDMock.callArgs = append(mmGetByConversationID.GetByConversationIDMock.callArgs, &mm_params)
	mmGetByConversationID.GetByConversationIDMock.mutex.Unlock()

	for _, e := range mmGetByConversationID.GetByConversationIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ma1, e.results.err
		}
	}

	if mmGetByConversationID.GetByConversationIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByConversationID.GetByConversationIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByConversationID.GetByConversationIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByConversationID.GetByConversationIDMock.defaultExpectation.paramPtrs

		mm_got := MessageRepositoryMockGetByConversationIDParams{ctx, conversationID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByConversationID.t.Errorf("MessageRepositoryMock.GetByConversationID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByConversationID.GetByConversationIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.conversationID != nil && !minimock.Equal(*mm_want_ptrs.conversationID, mm_got.conversationID) {
				mmGetByConversationID.t.Errorf("MessageRepositoryMock.GetByConversationID got unexpected parameter conversationID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByConversationID.GetByConversationIDMock.defaultExpectation.expectationOrigins.originConversationID, *mm_want_ptrs.conversationID, mm_got.conversationID, minimock.Diff(*mm_want_ptrs.conversationID, mm_got.conversationID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByConversationID.t.Errorf("MessageRepositoryMock.GetByConversationID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByConversationID.GetByConversationIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByConversationID.GetByConversationIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByConversationID.t.Fatal("No results are set for the MessageRepositoryMock.GetByConversationID")
		}
		return (*mm_results).ma1, (*mm_results).err
	}
	if mmGetByConversationID.funcGetByConversationID != nil {
		return mmGetByConversationID.funcGetByConversationID(ctx, conversationID)
	}
	mmGetByConversationID.t.Fatalf("Unexpected call to MessageRepositoryMock.GetByConversationID. %v %v", ctx, conversationID)
	return
}

// GetByConversationIDAfterCounter returns a count of finished MessageRepositoryMock.GetByConversationID invocations
func (mmGetByConversationID *MessageRepositoryMock) GetByConversationIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByConversationID.afterGetByConversationIDCounter)
}

// GetByConversationIDBeforeCounter returns a count of MessageRepositoryMock.GetByConversationID invocations
func (mmGetByConversationID *MessageRepositoryMock) GetByConversationIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByConversationID.beforeGetByConversationIDCounter)
}

// Calls returns a list of arguments used in each call to MessageRepositoryMock.GetByConversationID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByConversationID *mMessageRepositoryMockGetByConversationID) Calls() []*MessageRepositoryMockGetByConversationIDParams {
	mmGetByConversationID.mutex.RLock()

	argCopy := make([]*MessageRepositoryMockGetByConversationIDParams, len(mmGetByConversationID.callArgs))
	copy(argCopy, mmGetByConversationID.callArgs)

	mmGetByConversationID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByConversationIDDone returns true if the count of the GetByConversationID invocations corresponds
// the number of defined expectations
func (m *MessageRepositoryMock) MinimockGetByConversationIDDone() bool {
	if m.GetByConversationIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByConversationIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByConversationIDMock.invocationsDone()
}

// MinimockGetByConversationIDInspect logs each unmet expectation
func (m *MessageRepositoryMock) MinimockGetByConversationIDInspect() {
	for _, e := range m.GetByConversationIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MessageRepositoryMock.GetByConversationID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByConversationIDCounter := mm_atomic.LoadUint64(&m.afterGetByConversationIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByConversationIDMock.defaultExpectation != nil && afterGetByConversationIDCounter < 1 {
		if m.GetByConversationIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MessageRepositoryMock.GetByConversationID at\n%s", m.GetByConversationIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MessageRepositoryMock.GetByConversationID at\n%s with params: %#v", m.GetByConversationIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByConversationIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByConversationID != nil && afterGetByConversationIDCounter < 1 {
		m.t.Errorf("Expected call to MessageRepositoryMock.GetByConversationID at\n%s", m.funcGetByConversationIDOrigin)
	}

	if !m.GetByConversationIDMock.invocationsDone() && afterGetByConversationIDCounter > 0 {
		m.t.Errorf("Expected %d calls to MessageRepositoryMock.GetByConversationID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByConversationIDMock.expectedInvocations), m.GetByConversationIDMock.expectedInvocationsOrigin, afterGetByConversationIDCounter)
	}
}

type mMessageRepositoryMockGetPublic struct {
	optional           bool
	mock               *MessageRepositoryMock
	defaultExpectation *MessageRepositoryMockGetPublicExpectation
	expectations       []*MessageRepositoryMockGetPublicExpectation

	callArgs []*MessageRepositoryMockGetPublicParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MessageRepositoryMockGetPublicExpectation specifies expectation struct of the MessageRepository.GetPublic
type MessageRepositoryMockGetPublicExpectation struct {
	mock               *MessageRepositoryMock
	params             *MessageRepositoryMockGetPublicParams
	paramPtrs          *MessageRepositoryMockGetPublicParamPtrs
	expectationOrigins MessageRepositoryMockGetPublicExpectationOrigins
	results            *MessageRepositoryMockGetPublicResults
	returnOrigin       string
	Counter            uint64
}

// MessageRepositoryMockGetPublicParams contains parameters of the MessageRepository.GetPublic
type MessageRepositoryMockGetPublicParams struct {
	ctx    context.Context
	limit  int
	before *time.Time
}

// MessageRepositoryMockGetPublicParamPtrs contains pointers to parameters of the MessageRepository.GetPublic
type MessageRepositoryMockGetPublicParamPtrs struct {
	ctx    *context.Context
	limit  *int
	before **time.Time
}

// MessageRepositoryMockGetPublicResults contains results of the MessageRepository.GetPublic
type MessageRepositoryMockGetPublicResults struct {
	pa1 []models.PublicMessage
	err error
}

// MessageRepositoryMockGetPublicOrigins contains origins of expectations of the MessageRepository.GetPublic
type MessageRepositoryMockGetPublicExpectationOrigins struct {
	origin       string
	originCtx    string
	originLimit  string
	originBefore string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetPublic *mMessageRepositoryMockGetPublic) Optional() *mMessageRepositoryMockGetPublic {
	mmGetPublic.optional = true
	return mmGetPublic
}

// Expect sets up expected params for MessageRepository.GetPublic
func (mmGetPublic *mMessageRepositoryMockGetPublic) Expect(ctx context.Context, limit int, before *time.Time) *mMessageRepositoryMockGetPublic {
	if mmGetPublic.mock.funcGetPublic != nil {
		mmGetPublic.mock.t.Fatalf("MessageRepositoryMock.GetPublic mock is already set by Set")
	}

	if mmGetPublic.defaultExpectation == nil {
		mmGetPublic.defaultExpectation = &MessageRepositoryMockGetPublicExpectation{}
	}

	if mmGetPublic.defaultExpectation.paramPtrs != nil {
		mmGetPublic.mock.t.Fatalf("MessageRepositoryMock.GetPublic mock is already set by ExpectParams functions")
	}

	mmGetPublic.defaultExpectation.params = &MessageRepositoryMockGetPublicParams{ctx, limit, before}
	mmGetPublic.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetPublic.expectations {
		if minimock.Equal(e.params, mmGetPublic.defaultExpectation.params) {
			mmGetPublic.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetPublic.defaultExpectation.params)
		}
	}

	return mmGetPublic
}

// ExpectCtxParam1 sets up expected param ctx for MessageRepository.GetPublic
func (mmGetPublic *mMessageRepositoryMockGetPublic) ExpectCtxParam1(ctx context.Context) *mMessageRepositoryMockGetPublic {
	if mmGetPublic.mock.funcGetPublic != nil {
		mmGetPublic.mock.t.Fatalf("MessageRepositoryMock.GetPublic mock is already set by Set")
	}

	if mmGetPublic.defaultExpectation == nil {
		mmGetPublic.defaultExpectation = &MessageRepositoryMockGetPublicExpectation{}
	}

	if mmGetPublic.defaultExpectation.params != nil {
		mmGetPublic.mock.t.Fatalf("MessageRepositoryMock.GetPublic mock is already set by Expect")
	}

	if mmGetPublic.defaultExpectation.paramPtrs == nil {
		mmGetPublic.defaultExpectation.paramPtrs = &MessageRepositoryMockGetPublicParamPtrs{}
	}
	mmGetPublic.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetPublic.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetPublic
}

// ExpectLimitParam2 sets up expected param limit for MessageRepository.GetPublic
func (mmGetPublic *mMessageRepositoryMockGetPublic) ExpectLimitParam2(limit int) *mMessageRepositoryMockGetPublic {
	if mmGetPublic.mock.funcGetPublic != nil {
		mmGetPublic.mock.t.Fatalf("MessageRepositoryMock.GetPublic mock is already set by Set")
	}

	if mmGetPublic.defaultExpectation == nil {
		mmGetPublic.defaultExpectation = &MessageRepositoryMockGetPublicExpectation{}
	}

	if mmGetPublic.defaultExpectation.params != nil {
		mmGetPublic.mock.t.Fatalf("MessageRepositoryMock.GetPublic mock is already set by Expect")
	}

	if mmGetPublic.defaultExpectation.paramPtrs == nil {
		mmGetPublic.defaultExpectation.paramPtrs = &MessageRepositoryMockGetPublicParamPtrs{}
	}
	mmGetPublic.defaultExpectation.paramPtrs.limit = &limit
	mmGetPublic.defaultExpectation.expectationOrigins.originLimit = minimock.CallerInfo(1)

	return mmGetPublic
}

// ExpectBeforeParam3 sets up expected param before for MessageRepository.GetPublic
func (mmGetPublic *mMessageRepositoryMockGetPublic) ExpectBeforeParam3(before *time.Time) *mMessageRepositoryMockGetPublic {
	if mmGetPublic.mock.funcGetPublic != nil {
		mmGetPublic.mock.t.Fatalf("MessageRepositoryMock.GetPublic mock is already set by Set")
	}

	if mmGetPublic.defaultExpectation == nil {
		mmGetPublic.defaultExpectation = &MessageRepositoryMockGetPublicExpectation{}
	}

	if mmGetPublic.defaultExpectation.params != nil {
		mmGetPublic.mock.t.Fatalf("MessageRepositoryMock.GetPublic mock is already set by Expect")
	}

	if mmGetPublic.defaultExpectation.paramPtrs == nil {
		mmGetPublic.defaultExpectation.paramPtrs = &MessageRepositoryMockGetPublicParamPtrs{}
	}
	mmGetPublic.defaultExpectation.paramPtrs.before = &before
	mmGetPublic.defaultExpectation.expectationOrigins.originBefore = minimock.CallerInfo(1)

	return mmGetPublic
}

// Inspect accepts an inspector function that has same arguments as the MessageRepository.GetPublic
func (mmGetPublic *mMessageRepositoryMockGetPublic) Inspect(f func(ctx context.Context, limit int, before *time.Time)) *mMessageRepositoryMockGetPublic {
	if mmGetPublic.mock.inspectFuncGetPublic != nil {
		mmGetPublic.mock.t.Fatalf("Inspect function is already set for MessageRepositoryMock.GetPublic")
	}

	mmGetPublic.mock.inspectFuncGetPublic = f

	return mmGetPublic
}

// Return sets up results that will be returned by MessageRepository.GetPublic
func (mmGetPublic *mMessageRepositoryMockGetPublic) Return(pa1 []models.PublicMessage, err error) *MessageRepositoryMock {
	if mmGetPublic.mock.funcGetPublic != nil {
		mmGetPublic.mock.t.Fatalf("MessageRepositoryMock.GetPublic mock is already set by Set")
	}

	if mmGetPublic.defaultExpectation == nil {
		mmGetPublic.defaultExpectation = &MessageRepositoryMockGetPublicExpectation{mock: mmGetPublic.mock}
	}
	mmGetPublic.defaultExpectation.results = &MessageRepositoryMockGetPublicResults{pa1, err}
	mmGetPublic.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetPublic.mock
}

// Set uses given function f to mock the MessageRepository.GetPublic method
func (mmGetPublic *mMessageRepositoryMockGetPublic) Set(f func(ctx context.Context, limit int, before *time.Time) (pa1 []models.PublicMessage, err error)) *MessageRepositoryMock {
	if mmGetPublic.defaultExpectation != nil {
		mmGetPublic.mock.t.Fatalf("Default expectation is already set for the MessageRepository.GetPublic method")
	}

	if len(mmGetPublic.expectations) > 0 {
		mmGetPublic.mock.t.Fatalf("Some expectations are already set for the MessageRepository.GetPublic method")
	}

	mmGetPublic.mock.funcGetPublic = f
	mmGetPublic.mock.funcGetPublicOrigin = minimock.CallerInfo(1)
	return mmGetPublic.mock
}

// When sets expectation for the MessageRepository.GetPublic which will trigger the result defined by the following
// Then helper
func (mmGetPublic *mMessageRepositoryMockGetPublic) When(ctx context.Context, limit int, before *time.Time) *MessageRepositoryMockGetPublicExpectation {
	if mmGetPublic.mock.funcGetPublic != nil {
		mmGetPublic.mock.t.Fatalf("MessageRepositoryMock.GetPublic mock is already set by Set")
	}

	expectation := &MessageRepositoryMockGetPublicExpectation{
		mock:               mmGetPublic.mock,
		params:             &MessageRepositoryMockGetPublicParams{ctx, limit, before},
		expectationOrigins: MessageRepositoryMockGetPublicExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetPublic.expectations = append(mmGetPublic.expectations, expectation)
	return expectation
}

// Then sets up MessageRepository.GetPublic return parameters for the expectation previously defined by the When method
func (e *MessageRepositoryMockGetPublicExpectation) Then(pa1 []models.PublicMessage, err error) *MessageRepositoryMock {
	e.results = &MessageRepositoryMockGetPublicResults{pa1, err}
	return e.mock
}

// Times sets number of times MessageRepository.GetPublic should be invoked
func (mmGetPublic *mMessageRepositoryMockGetPublic) Times(n uint64) *mMessageRepositoryMockGetPublic {
	if n == 0 {
		mmGetPublic.mock.t.Fatalf("Times of MessageRepositoryMock.GetPublic mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetPublic.expectedInvocations, n)
	mmGetPublic.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetPublic
}

func (mmGetPublic *mMessageRepositoryMockGetPublic) invocationsDone() bool {
	if len(mmGetPublic.expectations) == 0 && mmGetPublic.defaultExpectation == nil && mmGetPublic.mock.funcGetPublic == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetPublic.mock.afterGetPublicCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetPublic.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetPublic implements mm_repository.MessageRepository
func (mmGetPublic *MessageRepositoryMock) GetPublic(ctx context.Context, limit int, before *time.Time) (pa1 []models.PublicMessage, err error) {
	mm_atomic.AddUint64(&mmGetPublic.beforeGetPublicCounter, 1)
	defer mm_atomic.AddUint64(&mmGetPublic.afterGetPublicCounter, 1)

	mmGetPublic.t.Helper()

	if mmGetPublic.inspectFuncGetPublic != nil {
		mmGetPublic.inspectFuncGetPublic(ctx, limit, before)
	}

	mm_params := MessageRepositoryMockGetPublicParams{ctx, limit, before}

	// Record call args
	mmGetPublic.GetPublicMock.mutex.Lock()
	mmGetPublic.GetPublicMock.callArgs = append(mmGetPublic.GetPublicMock.callArgs, &mm_params)
	mmGetPublic.GetPublicMock.mutex.Unlock()

	for _, e := range mmGetPublic.GetPublicMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pa1, e.results.err
		}
	}

	if mmGetPublic.GetPublicMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetPublic.GetPublicMock.defaultExpectation.Counter, 1)
		mm_want := mmGetPublic.GetPublicMock.defaultExpectation.params
		mm_want_ptrs := mmGetPublic.GetPublicMock.defaultExpectation.paramPtrs

		mm_got := MessageRepositoryMockGetPublicParams{ctx, limit, before}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetPublic.t.Errorf("MessageRepositoryMock.GetPublic got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPublic.GetPublicMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.limit != nil && !minimock.Equal(*mm_want_ptrs.limit, mm_got.limit) {
				mmGetPublic.t.Errorf("MessageRepositoryMock.GetPublic got unexpected parameter limit, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPublic.GetPublicMock.defaultExpectation.expectationOrigins.originLimit, *mm_want_ptrs.limit, mm_got.limit, minimock.Diff(*mm_want_ptrs.limit, mm_got.limit))
			}

			if mm_want_ptrs.before != nil && !minimock.Equal(*mm_want_ptrs.before, mm_got.before) {
				mmGetPublic.t.Errorf("MessageRepositoryMock.GetPublic got unexpected parameter before, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPublic.GetPublicMock.defaultExpectation.expectationOrigins.originBefore, *mm_want_ptrs.before, mm_got.before, minimock.Diff(*mm_want_ptrs.before, mm_got.before))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetPublic.t.Errorf("MessageRepositoryMock.GetPublic got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetPublic.GetPublicMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetPublic.GetPublicMock.defaultExpectation.results
		if mm_results == nil {
			mmGetPublic.t.Fatal("No results are set for the MessageRepositoryMock.GetPublic")
		}
		return (*mm_results).pa1, (*mm_results).err
	}
	if mmGetPublic.funcGetPublic != nil {
		return mmGetPublic.funcGetPublic(ctx, limit, before)
	}
	mmGetPublic.t.Fatalf("Unexpected call to MessageRepositoryMock.GetPublic. %v %v %v", ctx, limit, before)
	return
}

// GetPublicAfterCounter returns a count of finished MessageRepositoryMock.GetPublic invocations
func (mmGetPublic *MessageRepositoryMock) GetPublicAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetPublic.afterGetPublicCounter)
}

// GetPublicBeforeCounter returns a count of MessageRepositoryMock.GetPublic invocations
func (mmGetPublic *MessageRepositoryMock) GetPublicBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetPublic.beforeGetPublicCounter)
}

// Calls returns a list of arguments used in each call to MessageRepositoryMock.GetPublic.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetPublic *mMessageRepositoryMockGetPublic) Calls() []*MessageRepositoryMockGetPublicParams {
	mmGetPublic.mutex.RLock()

	argCopy := make([]*MessageRepositoryMockGetPublicParams, len(mmGetPublic.callArgs))
	copy(argCopy, mmGetPublic.callArgs)

	mmGetPublic.mutex.RUnlock()

	return argCopy
}

// MinimockGetPublicDone returns true if the count of the GetPublic invocations corresponds
// the number of defined expectations
func (m *MessageRepositoryMock) MinimockGetPublicDone() bool {
	if m.GetPublicMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetPublicMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetPublicMock.invocationsDone()
}

// MinimockGetPublicInspect logs each unmet expectation
func (m *MessageRepositoryMock) MinimockGetPublicInspect() {
	for _, e := range m.GetPublicMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MessageRepositoryMock.GetPublic at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetPublicCounter := mm_atomic.LoadUint64(&m.afterGetPublicCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetPublicMock.defaultExpectation != nil && afterGetPublicCounter < 1 {
		if m.GetPublicMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MessageRepositoryMock.GetPublic at\n%s", m.GetPublicMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MessageRepositoryMock.GetPublic at\n%s with params: %#v", m.GetPublicMock.defaultExpectation.expectationOrigins.origin, *m.GetPublicMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetPublic != nil && afterGetPublicCounter < 1 {
		m.t.Errorf("Expected call to MessageRepositoryMock.GetPublic at\n%s", m.funcGetPublicOrigin)
	}

	if !m.GetPublicMock.invocationsDone() && afterGetPublicCounter > 0 {
		m.t.Errorf("Expected %d calls to MessageRepositoryMock.GetPublic at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetPublicMock.expectedInvocations), m.GetPublicMock.expectedInvocationsOrigin, afterGetPublicCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *MessageRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockGetByConversationIDInspect()

			m.MinimockGetPublicInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *MessageRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *MessageRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockGetByConversationIDDone() &&
		m.MinimockGetPublicDone()
}
